sudo: false
language: scala
scala:
  - 2.12.8
script:
  - sbt "project core" ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - sbt "project jruby" ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
jdk:
  - openjdk8
  - openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)
