sudo: false
language: scala
scala:
  - 2.12.8

jobs:
  include:
    - stage: test
      script:
        - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: deploy
      script:
        - skip
      deploy:
        provider: script
        script: sbt publish
        on:
          tags: true
