addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"              % "3.10.0")
addSbtPlugin("com.github.sbt"   % "sbt-pgp"                   % "2.2.1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"              % "2.5.2")
addSbtPlugin("org.typelevel"    % "sbt-tpolecat"              % "0.5.0")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.3.1")
